### Testar o cadastro de Usuário
POST http://localhost/Somos/usuario/cadastrar
Content-Type: application/json

{
    "nome": "Vinícius Fernandes",
    "email": "vini.teste.psi@email.com",
    "senha": "123",
    "tipo": "psicologo"
}

###

### Testar o Login
POST http://localhost/Somos/usuario/login
Content-Type: application/json


{
    "email": "vini.teste.psi@email.com",
    "senha": "123"
}